"""Initial + sons daughters

Revision ID: 71a6c9fbec33
Revises: 
Create Date: 2026-04-18 01:10:53.618191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a6c9fbec33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_type', sa.String(length=30), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('jitsi_room', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_notes', sa.Text(), nullable=True),
    sa.Column('summary_prayers', sa.Text(), nullable=True),
    sa.Column('summary_teaching', sa.Text(), nullable=True),
    sa.Column('summary_scriptures', sa.Text(), nullable=True),
    sa.Column('summary_action_items', sa.Text(), nullable=True),
    sa.Column('summary_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=True),
    sa.Column('answered_testimony', sa.Text(), nullable=True),
    sa.Column('prayer_count', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sons_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disciple_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('disciple_applied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('disciple_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('disciple_testimony', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disciple_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disciple_reason')
        batch_op.drop_column('disciple_testimony')
        batch_op.drop_column('disciple_approved_at')
        batch_op.drop_column('disciple_applied_at')
        batch_op.drop_column('disciple_status')

    op.drop_table('sons_announcements')
    op.drop_table('prayer_requests')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
